# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  rust: stable
repos:
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.4
    hooks:
      - id: shellcheck
        args: ["-x"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: cargo-check
      - id: clippy
        args: ["--all-features", "--", "-D", "warnings", "-A", "unknown-lints"]
  - repo: local
    hooks:
      - id: cargo-machete
        name: cargo-machete
        entry: cargo machete
        pass_filenames: false
        language: rust
        additional_dependencies:
          - "cli:cargo-machete:0.5.0"
      - id: prevent-dbg
        name: prevent dbg!(..) in rust code
        language: pygrep
        entry: dbg!
        types:
          - "rust"
